- id: vtr
  name: vscode task runner
  description: "Run tasks from .vscode/tasks.json on the command line"
  entry: vtr
  language: python
  minimum_pre_commit_version: 2.9.2
  pass_filenames: false
  always_run: true